
export const FETCH_BLOGS = 'FETCH_BLOGS'


export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';


export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';


export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';